[package]
name = "vl_big_ints_modulo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto-impl-ops = "0.2.1"
vl_big_ints = {path = "../cp1"}

[dev-dependencies]
csv = "1.3.0"
rand = "0.8.5"
